language: java
install: true
install: gradle wrapper --gradle-version 4.2


jdk:
  - oraclejdk8

script:
  - ./gradlew build
  - ./gradlew sonarqube   -Dsonar.projectKey=chiwailau_Battleship_Java   -Dsonar.organization=chiwailau-github   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=04b01582cd77339ea883c8349f9793d0ade7956b


notifications:
  slack: psdhk:lUVOpDG7b4yKHrlg5eLpBxXI
